version: "3"

services:
  source-postgres:
    image: postgres:bullseye
    hostname: source-postgres
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - my-network

  bridge-minio:
    image: minio/minio:latest
    restart: always
    command: server --console-address ":9001" /data/minio/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9002:9002
      - 9001:9001
    networks:
      - my-network

  create-minio-bucket:
    image: minio/mc
    depends_on:
      - bridge-minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://bridge-minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/replibyte-test;
      /usr/bin/mc mb myminio/replibyte-test;
      /usr/bin/mc policy download myminio/replibyte-test;
      exit 0;
      "
    networks:
      - my-network

  dev-env:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../algo:/algo
      - ../src:/src
      - ../db:/db
    ports:
      - "8000:8000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
